# Generated by Django 5.2.6 on 2025-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dimensions', models.CharField(max_length=100)),
                ('stitch_details', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
